#!/bin/bash

source "env.sh"

$CONTAINER_TOOL build \
	--build-arg MPLABX_VERSION=$MPLABX_VERSION \
	--build-arg XC_TOOLCHAIN=$XC_TOOLCHAIN \
	--build-arg XC_TOOLCHAIN_VERSION=$XC_TOOLCHAIN_VERSION \
	--build-arg ATPACK_NAME=$ATPACK_NAME \
	--build-arg ATPACK_VERSION=$ATPACK_VERSION \
	--build-arg USER_NAME=$USER_NAME \
	--build-arg USER_ID=$USER_ID \
	--build-arg GROUP_ID=$GROUP_ID \
	. \
	-t "${CONTAINER_IMAGE_NAME}:$MINOR_VER" \
	-t "${CONTAINER_IMAGE_NAME}:$MAJOR_VER" \
	-t "${CONTAINER_IMAGE_NAME}:latest" \
	-t "${REMOTE_REGISTRY}${FOLDER}${CONTAINER_IMAGE_NAME}:$MINOR_VER" \
	-t "${REMOTE_REGISTRY}${FOLDER}${CONTAINER_IMAGE_NAME}:$MAJOR_VER" \
	-t "${REMOTE_REGISTRY}${FOLDER}${CONTAINER_IMAGE_NAME}:latest"
