# This environment file contains environment values for shell support scripts.
#
# Example values
# CONTAINER_TOOL=podman
# CONTAINER_IMAGE_NAME=arch_mplabx
# REMOTE_REGISTRY="<registry_url>:5000/"
# FOLDER="mplabx/"
# MAJOR_VER=1
# MINOR_VER=$MAJOR_VER.0
CONTAINER_TOOL=podman
CONTAINER_IMAGE_NAME=arch_mplabx
REMOTE_REGISTRY=""
FOLDER="mplabx/"
MAJOR_VER=1
MINOR_VER=$MAJOR_VER.8

# User
USER_NAME=developer
USER_ID=1000
GROUP_ID=1000

# Build ARG vars
MPLABX_VERSION=6.20
XC_TOOLCHAIN=xc32
XC_TOOLCHAIN_VERSION=4.35
ATPACK_NAME=PIC32MZ-EF_DFP
ATPACK_VERSION=1.4.168
SIM_ATPACK_NAME=Simulator_TP
SIM_ATPACK_VERSION=1.7.660
CURIOSITY_ATPACK_NAME=PKOB4_TP
CURIOSITY_ATPACK_VERSION=1.14.1168
