#!/bin/bash

source "env.sh"

$CONTAINER_TOOL push "${REMOTE_REGISTRY}${FOLDER}${CONTAINER_IMAGE_NAME}:${MINOR_VER}"
$CONTAINER_TOOL push "${REMOTE_REGISTRY}${FOLDER}${CONTAINER_IMAGE_NAME}:${MAJOR_VER}"
$CONTAINER_TOOL push "${REMOTE_REGISTRY}${FOLDER}${CONTAINER_IMAGE_NAME}:latest"
